/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BanditView.java
 *
 * Created on Oct 30, 2013, 8:15:10 PM
 */
package aufgabe05b.View;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import logger.OhmLogger;

/**
 * View of the slot machine
 * @author christian
 */
public class BanditView extends javax.swing.JFrame {

    private ArrayList<ImageIcon> images;
    
    /**
     * Creates a new BanditView object
     */
    public BanditView() 
    {
        initComponents();
        this.loadImages();
        btnStop.setEnabled(false);
        OhmLogger.info("BanditView is all set up");
    }
    
    /**
     * Show dialog is user won
     */
    public void showWinDialog()
    {
        OhmLogger.info("win dialog shown");
        
        JOptionPane.showMessageDialog(rootPane, "Herzlichen Glückwunsch!!!",
                    "Gewonnen", JOptionPane.INFORMATION_MESSAGE);
    }
    
    /**
     * Show dialog if user lost
     */
    public void showLoseDialog()
    {
        OhmLogger.info("lose dialog shown");
        
        JOptionPane.showMessageDialog(rootPane, "Leider keine Credits mehr...",
                    "Verloren", JOptionPane.INFORMATION_MESSAGE);
    }
    
    /**
     * Load all images
     */
    private void loadImages()
    {
        String path = "/assets/";
        
        images = new ArrayList<ImageIcon>();
        images.add(new ImageIcon(this.getClass().getResource(path + "BeanAdd24.gif")));
        images.add(new ImageIcon(this.getClass().getResource(path + "Cut24.gif")));
        images.add(new ImageIcon(this.getClass().getResource(path + "Delete24.gif")));
        images.add(new ImageIcon(this.getClass().getResource(path + "Find24.gif")));
        images.add(new ImageIcon(this.getClass().getResource(path + "Help24.gif")));
        images.add(new ImageIcon(this.getClass().getResource(path + "Home24.gif")));
        images.add(new ImageIcon(this.getClass().getResource(path + "Host24.gif")));
        images.add(new ImageIcon(this.getClass().getResource(path + "Volume24.gif")));
        images.add(new ImageIcon(this.getClass().getResource(path + "WebComponent24.gif")));
    }
    
    /**
     * Select icon
     * @param number Requested item
     * @return Selected icon
     */
    public ImageIcon selectIcon(int number)
    {
        return images.get(number-1);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbSlot1 = new javax.swing.JLabel();
        lbSlot2 = new javax.swing.JLabel();
        lbSlot3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbCredits = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Einarmiger Bandit");

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        lbSlot1.setBackground(new java.awt.Color(-1,true));
        lbSlot1.setFont(new java.awt.Font("Dialog", 0, 48));
        lbSlot1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSlot1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbSlot1.setOpaque(true);
        jPanel1.add(lbSlot1);

        lbSlot2.setBackground(new java.awt.Color(-1,true));
        lbSlot2.setFont(new java.awt.Font("Dialog", 0, 48));
        lbSlot2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSlot2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbSlot2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbSlot2.setOpaque(true);
        jPanel1.add(lbSlot2);

        lbSlot3.setBackground(new java.awt.Color(-1,true));
        lbSlot3.setFont(new java.awt.Font("Dialog", 0, 48));
        lbSlot3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSlot3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbSlot3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbSlot3.setOpaque(true);
        jPanel1.add(lbSlot3);

        jLabel1.setText("Credits");
        jPanel3.add(jLabel1);

        lbCredits.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel3.add(lbCredits);

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        btnStart.setText("Start");
        jPanel2.add(btnStart);

        btnStop.setText("Stop");
        jPanel2.add(btnStop);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-258)/2, (screenSize.height-155)/2, 258, 155);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BanditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BanditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BanditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BanditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new BanditView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbCredits;
    private javax.swing.JLabel lbSlot1;
    private javax.swing.JLabel lbSlot2;
    private javax.swing.JLabel lbSlot3;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnStart
     */
    public javax.swing.JButton getBtnStart() {
        return btnStart;
    }

    /**
     * @return the btnStop
     */
    public javax.swing.JButton getBtnStop() {
        return btnStop;
    }

    /**
     * @return the lbSlot1
     */
    public javax.swing.JLabel getLbSlot1() {
        return lbSlot1;
    }

    /**
     * @return the lbSlot2
     */
    public javax.swing.JLabel getLbSlot2() {
        return lbSlot2;
    }

    /**
     * @return the lbSlot3
     */
    public javax.swing.JLabel getLbSlot3() {
        return lbSlot3;
    }

    /**
     * @return the lbCredits
     */
    public javax.swing.JLabel getLbCredits() {
        return lbCredits;
    }

}
